#!/bin/sh

this_dir="$(cd "$(dirname "$0")" && pwd)"
if [ -e "$this_dir/main.py" ] && [ "$this_dir" != "$CCP4/bin" ]; then
  # development (source tree) version
  if [ -e "$CCP4/bin/ccp4-python" ]; then
    exec "$CCP4/bin/ccp4-python" "$this_dir/main.py" "$@"
  else
    exec python2.7 "$this_dir/main.py" "$@"
  fi
else
  # installed module
  exec "$CCP4/bin/ccp4-python" -m dimple "$@"
fi
